name: CI

on:
  pull_request:
  push:

jobs:
  x86:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - run: nix build
    - run: nix flake check

  aarch64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - run: |
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
    - run: |
        OPTIONS="--option system aarch64-linux
                 --option sandbox false
                 --extra-platforms aarch64-linux"
        nix build $OPTIONS .#defaultPackage.aarch64-linux
