name: CI

on:
  pull_request:
  push:

jobs:
  tests_20_09:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Run tests
      run: |
        nix-build -E 'with import <nixpkgs> {}; callPackage ./. { }'
  tests_unstable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run tests
      run: |
        nix-build -E 'with import <nixpkgs> {}; callPackage ./. { }'

